# Theme configuration
theme: jekyll-theme-cayman
title: C0ZEN's wiki
description: Just a bunch of stuff about Front-End stuff to help me (and maybe you) to have access to good pratices, reminders and snippet.
author: C0ZEN
author_email: geoffrey.testelin@gmail.com
permalink: pretty

# Url
homePageUrl: https://c0zen.github.io/wiki/
baseUrl: https://c0zen.github.io/wiki/
