# Theme configuration
theme: jekyll-theme-cayman
title: C0ZEN's AngularJS wiki
description: Just a bunch of stuff about Angular to help me (and maybe you) to have access to good pratices, reminders and snippet.
author: C0ZEN
author_email: geoffrey.testelin@gmail.com
permalink: pretty

# Url
baseUrl: https://c0zen.github.io/angular-wiki/
